services:
  geo-api:
    image: geo-ner-trainer
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./final_model:/app/model
    ports:
      - "8000:8000"
